# Generated by Django 5.2.8 on 2025-12-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_delivered_at_order_shipped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="", max_length=20),
        ),
    ]
