# Generated by Django 5.2.7 on 2025-12-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_order_address_order_city_order_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Created",
                max_length=50,
            ),
        ),
    ]
