# Generated by Django 6.0 on 2025-12-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_productwatchlist_stockalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="productwatchlist",
            name="custom_threshold",
            field=models.IntegerField(
                blank=True,
                help_text="Custom alert threshold for this specific product (overrides global setting)",
                null=True,
            ),
        ),
    ]
