# Generated by Django 6.0 on 2025-12-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productwatchlist_custom_threshold"),
        ("store", "0007_review"),
    ]

    operations = []
