# Generated by Django 6.0 on 2025-12-11 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_merge_20251208_1824"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productwatchlist",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stockalert",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="stockalert",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productwatchlist",
            name="auto_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productwatchlist",
            name="custom_threshold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productwatchlist",
            name="last_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="stockalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notified", False)),
                fields=("user", "product"),
                name="unique_active_alert",
            ),
        ),
    ]
