# Generated by Django 6.0 on 2025-12-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_stock_email_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Email when watched items are running low",
                    ),
                ),
                (
                    "restock_email_alerts",
                    models.BooleanField(
                        default=True, help_text="Email when out-of-stock items restock"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Alert when stock is at or below this number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User preferences",
            },
        ),
    ]
